"""empty message

Revision ID: f8e559789616
Revises: 0e59108b5aa8
Create Date: 2021-03-03 16:11:51.284394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8e559789616'
down_revision = '0e59108b5aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favoritos', sa.Column('personaje_id', sa.String(length=250), nullable=True))
    op.add_column('favoritos', sa.Column('planeta_id', sa.String(length=250), nullable=True))
    op.drop_constraint('favoritos_ibfk_2', 'favoritos', type_='foreignkey')
    op.drop_constraint('favoritos_ibfk_1', 'favoritos', type_='foreignkey')
    op.create_foreign_key(None, 'favoritos', 'personajes', ['personaje_id'], ['id'])
    op.create_foreign_key(None, 'favoritos', 'planetas', ['planeta_id'], ['id'])
    op.drop_column('favoritos', 'planetas_name')
    op.drop_column('favoritos', 'personajes_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favoritos', sa.Column('personajes_name', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('favoritos', sa.Column('planetas_name', mysql.VARCHAR(length=250), nullable=True))
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.create_foreign_key('favoritos_ibfk_1', 'favoritos', 'personajes', ['personajes_name'], ['name'])
    op.create_foreign_key('favoritos_ibfk_2', 'favoritos', 'planetas', ['planetas_name'], ['name'])
    op.drop_column('favoritos', 'planeta_id')
    op.drop_column('favoritos', 'personaje_id')
    # ### end Alembic commands ###
